apiVersion: apik10.kasten.io/v1alpha1
kind: K10
metadata:
  name: k10
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec:
  auth:
    openshift:
      enabled: true
      serviceAccount: "k10-dex-sa"
      clientSecret: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlpIZDJNOG5pdVAwRkk3aEQyb2g3UXRFWVk4clBFYUVBd1RSZVo0MkxTQU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrYXN0ZW4taW8iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiazEwLWRleC1zYS1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiazEwLWRleC1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjkxNWI5MmExLWRhMGMtNGM5Zi05MThiLWZkMzQ3ZTA0NGZhMCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprYXN0ZW4taW86azEwLWRleC1zYSJ9.CCRKcaIbWUmiROalDukCyyT59cHtgc5OP7471ClyZtHE9bCBN8oe6TnWcE5HfJuy2wO1GVMkDENbHs0oIJXBWDaieOBTGjKCauUv4RxGPGNs_fyq5TbLfvlEXPyu-qjNpjsTn7IgQzePPe_KCYBUUqz1N4fjLxZmy321gB5RmLUpdomI8TKVJS2PUy8YdB1XSFaTJRQvPCdIYnBY3hMfb1Hidd1ujZmnuqaL6yUEyxeW0StclNBEg8U43ttiElwqnUlmh3ozscDHm8OFp--ggJt9P4WkJypxEFzhda67h8QvX5wl6mfePFsLERm1qjRA8rCmyCMVoJdASxrrhyahzI6FfdB6iOe2EGTWf5hDPRrCiqBI-N5VMXHtpmzo-aFEGn32z0FCTKTVZVYgeFUc8Oxj9iQv5L47s5SMDC8egyzevm9EY5RSdLnLbD-o6yHMi2A0HaU9-EVceUtx-m5YzpuIOf9OYwWKMI2t4LhGSiOssLhejbxdKITNB0NKjtaekCgVEhOiy8n_WxjSdZH2MLWca94syR51_lRfa4QQdu2wCVPQgtdirEs3fti-c2eFfgtInEg1r5Mf-oTFhhRPbYbSjlJJuoTDuaXyIA1GDIM-JGTXjw9nGJPUfWR-XeDgz2hXVaSrlD77Cmr6oCm-537NhTzqMVq0oM3Vf_e0_e8"
      dashboardURL: "https://k10-route-kasten-io.apps.bm2.redhat.hpecic.net/k10"
      openshiftURL: "https://api.bm2.redhat.hpecic.net:6443"
      insecureCA: false
  cacertconfigmap:
    name: "custom-ca-bundle-store"
  global:
    persistence:
      storageClass: "ocs-storagecluster-ceph-rbd"
  route:
    enabled: true
    tls:
      enabled: true
