apiVersion: batch/v1
kind: Job
metadata:
  name: k10-instance
  namespace: kasten-io
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.12
          command:
            - /bin/bash
            - -c
            - |
              oc adm policy add-role-to-user admin system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller -n kasten-io
              cat <<EOF | kubectl create -f -
              apiVersion: apik10.kasten.io/v1alpha1
              kind: K10
              metadata:
                name: k10
                namespace: kasten-io
                annotations:
                  argocd.argoproj.io/sync-wave: "4"
              spec:
                auth:
                  basicAuth:
                    enabled: false
                  tokenAuth:
                    enabled: true
                route:
                  enabled: true
                tls:
                  enabled: true
                scc:
                  create: true
                EOF

          name: k10-instance
          env:
            - name: SLEEP
              value: "5"
      serviceAccountName: k10-kasten-operator-rhmp-controller-manager
      restartPolicy: Never
